language: node_js
node_js: '7'

cache:
  directories:
    - node_modules

env:
  global:
    - secure: "dPLtyrTm8xc9x7b7Pd9EpWZ1D1B2Y58e3N5jstP33IIJZWRm7FhXc6lRlRdhXhgZZCxY2DrUv4fIMCeaA2jFkEpKzXCGRWIG5Xo6C5YFsouJ+vQgeB/MX4/df72tSkwDv6pVSbQU6HBLDWWNWduvFIqGCapdmfvSezqu2FjMC6OYHVTThov8jxIqk4iJuxzY+PQhlJrIq9CqB/D32KK0JvX80X0qQB/9yiNLqyzoWwHHDWHFzJP46pyEWrcKmQmwv/CC7ZwRCXPcCttT/mzgqgS4mwq3k62Zyr9JpBgq3BnOuDEhgdyG/odYy4lSX9ih3EpRTv9Ix3OPF+r9XoUtEqRtAGa2HBSaGxL9Qz5TDMBDQvHYFv3QVaBJDyT4paD5aSJGEPNM0mRlSxgvjg6zDl7VKk2Fc3+2rx3vBI1d6mLn74ETu4BZ+M7ifUJCIZ8Aj+sj/hB5/viAjofwsHsB+s4sQ+T2PrRXTjvQZhyzLveHSjjtrB+/yB4rCUjrU9A8ntBdqoqA8cCyNhUxVzjPKABVkFqjvHpwvD6VhIHSMKDVFRKg2j4Ws0d2hllJCP/Gjsttqi0KzV0QPYpHOfEf023kN4vszjmXtLf7GmWxn+tLTxu5g1mKDpFFSRD3Fc/6zTEMDc5+MqGumBx+ZZvymAVYipfyJaVzvq3LX2DbfKM="
    - GOOGLE_EXTENSION_ID='cjnfkpniglbbhifpkfnclpndpbhmfllh'

before_install:

install:
  - npm install

script:
  - npm run lint

after_success:
  - if [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_TAG" = "" ]; then
      exit 0;
    fi
  - npm run deploy
