language: node_js
node_js: "9"
sudo: required

matrix:
  include:
    - os: linux
      env:
        - BROWSER='chrome'
        - DISPLAY=':99.0'
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
    - os: linux
      env:
        - BROWSER='firefox'
        - DISPLAY=':99.0'
      addons:
        firefox: latest-dev
    - os: osx
      env:
        - BROWSER='chrome'
        - HOMEBREW_CASK_OPTS='--appdir=/Applications'
    - os: osx
      env:
        - BROWSER='firefox'
        - HOMEBREW_CASK_OPTS='--appdir=/Applications'

cache:
  directories:
    - node_modules

env:
  global:
    - secure: "CpG815LM2rpdo6V3loMJVP6k7yca8Xm61aiu4z9znL31RVZhMVezOqiMp95YxT9WCyFYJnUbbz13g9Sr6Wh4qgagiCUUGOPRQPWGdl0NLhVtrRBgT3UiHTnKHhSP8qk8ggvLrbr3oxQeG04RAB5FYN0WGx4XfEpqnVri1Sq92eT2OvSt6VUYb7M42L/1qGb7aZuOQuq7hid0wNE6f5udSopqRTSpiKxu1KCez0IPl/8xOznOJ3vqxb4G494iHlCWPKh/FBVo2P8o2FHGxG71bCVd7Vgsgh2RBChMs+hhcSRRLt0PjFjIzGLuF10j/AsqtGR3MJhUZ9k6R0sj382EUb0+AI/NkXlZqn/96c3OxExA3c1YBE4qO0gsp8L9RqAXhMQ/3k1L/hpCDnqKdIFdsH9rv6xpKD3XGj0w1WoODXfoC7SgvmdH/X0onvU74CIPcNGRzHLrlzdRw8vwk7Z3n0lo19OYd7zq18TYymKGQVrjG/ztW8KkMpcgS+hjz7o/ytjPlcB/8UZw4Xo17ANLvmCp09O6MGg5otqkfU/0Phz79r0JPmckohmQG3i7sqQYdrBO9FB1Z9RdOI9hZzljldatx6niNAWBdbPTWnFYwVp4OhmXiCOCILOoJ5g+h7bcJXU//ZYn8BzNzMXyPGyA/Z/3axJNpKNH6XxvGMN4kW8="
    - GOOGLE_EXTENSION_ID='cjnfkpniglbbhifpkfnclpndpbhmfllh'

before_install:
  - bin/.travis/before_install

install:
  - npm install

before_script:
  - bin/.travis/before_script

script:
  - bin/.travis/script

after_success:
  - bin/.travis/after_success
