language: node_js

matrix:
  include:
    - os: linux
      node_js: "9"
      sudo: required
      env: DISPLAY=':99.0'
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
    - os: osx
      node_js: "9"
      sudo: required
      env: HOMEBREW_CASK_OPTS='--appdir=/Applications'

cache:
  directories:
    - node_modules

env:
  global:
    - secure: "Lr7BafmQxYiBbvwxdfdyOGpYexK5dRBIf56lYaQIL4Xh7E3GrtgNjZGKBR/2mZ7KSzxcqqrAmBH5vh6ZQ7jWFWaA1U+lh+Y+Mh9Om3gALVpk6lhdwlfmMccTJhrx5qwL5J3+KIcxVl1C2dSwmmEIMF1ekgZyrXCCgp/fof+iT2vx+wvtpSRLM2qkVLRK5dPwB0AU/VTlHRK+7KKS6x9PJ88+eZhmbvI4jC7wIfUVLJ0FwyNYu5YmfoWgeQLddeePXn+BZ/Gtmx/oM8K4iZ24162GJchJaUZJqTKOFhBkOJmOx5KrFFctpjkFq+WHATxSOafUAbTlAz9cE8ukA7xOfODrcYyt5DQEymR6iZLi7ZZnqEjeXihUUf+FNG9mYqyJMj+RRhu9Akrf4yOF/H3eZqVU3ZbZmDKoH0Rv46GlrzBP1cOwWXmKFSJ5vNBslIwWqEPFbWwLFLoba+ur2O2jsUZhxAak6cygEokqSYnbvPYa4MHH3pxswBQJhqFH88NhtUalOiWGxZtg9SPWvKydXKAWgpZEs/n0m7+H4FSyyTkMYKppc6XcbK0uHg5qwSGkvt7W/HhTMQ8uujAgGxBePBNQxjoZeScO+mHliKDMlbDmYeBtN8+nkvoQXvpAhaLbRC/xMFcnC2MB3aRP91912ZdBK55630W2ZTJjY6433ZI="
    - GOOGLE_EXTENSION_ID='cjnfkpniglbbhifpkfnclpndpbhmfllh'

before_install:
  - bin/.travis/before_install

install:
  - npm install

before_script:
  - bin/.travis/before_script

script:
  - bin/.travis/script

after_success:
  - bin/.travis/after_success
