language: node_js
node_js: '7'

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

env:
  global:
    - secure: "Lr7BafmQxYiBbvwxdfdyOGpYexK5dRBIf56lYaQIL4Xh7E3GrtgNjZGKBR/2mZ7KSzxcqqrAmBH5vh6ZQ7jWFWaA1U+lh+Y+Mh9Om3gALVpk6lhdwlfmMccTJhrx5qwL5J3+KIcxVl1C2dSwmmEIMF1ekgZyrXCCgp/fof+iT2vx+wvtpSRLM2qkVLRK5dPwB0AU/VTlHRK+7KKS6x9PJ88+eZhmbvI4jC7wIfUVLJ0FwyNYu5YmfoWgeQLddeePXn+BZ/Gtmx/oM8K4iZ24162GJchJaUZJqTKOFhBkOJmOx5KrFFctpjkFq+WHATxSOafUAbTlAz9cE8ukA7xOfODrcYyt5DQEymR6iZLi7ZZnqEjeXihUUf+FNG9mYqyJMj+RRhu9Akrf4yOF/H3eZqVU3ZbZmDKoH0Rv46GlrzBP1cOwWXmKFSJ5vNBslIwWqEPFbWwLFLoba+ur2O2jsUZhxAak6cygEokqSYnbvPYa4MHH3pxswBQJhqFH88NhtUalOiWGxZtg9SPWvKydXKAWgpZEs/n0m7+H4FSyyTkMYKppc6XcbK0uHg5qwSGkvt7W/HhTMQ8uujAgGxBePBNQxjoZeScO+mHliKDMlbDmYeBtN8+nkvoQXvpAhaLbRC/xMFcnC2MB3aRP91912ZdBK55630W2ZTJjY6433ZI="
    - GOOGLE_EXTENSION_ID='cjnfkpniglbbhifpkfnclpndpbhmfllh'
    - DISPLAY=':99.0'
    - CHROME_BIN='chromedriver'

before_install:
  - DRIVER_VER=$(curl -sL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
  - curl -sOJ "https://chromedriver.storage.googleapis.com/$DRIVER_VER/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin

install:
  - npm install

before_script:
  - sh -e /etc/init.d/xvfb start
  - pushd ..
  - google-chrome --pack-extension=$OLDPWD
  - mv *.crx $OLDPWD/
  - popd

script:
  - npm run lint
  - npm test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_TAG" = "" ]; then
      exit 0;
    fi
  - npm run deploy
