version: 1.0.{build}
skip_tags: true

environment:
  FIREFOX_APPLICATION_ID: '{7cd0430c-a4e3-4076-9d93-96ee9185e0a5}'
  TEST_TWITTER_USERNAME:
    secure: dI/HBFi3oFaiHEqm1mb2Sw==
  TEST_TWITTER_PASSWORD:
    secure: Bzu68YBGyvleQ4hMd9PFC1yhC77pBzQGB2awGbENXsrHRsziG1TyUWCOS8FsSPOG

  matrix:
    - BROWSER: chrome
    - BROWSER: firefox

cache: node_modules
build: off
deploy: off

install:
  - ps: Import-Module .\bin\appveyor\modules.psm1
  - ps: Invoke-AppVeyorInstall
  - cmd: npm install

test_script:
  - cmd: npm run build
  - cmd: npm test
